name: .NET CI


on:
  push:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Entity Tests
        run: dotnet restore ./Tests/Entities.UnitTests/*.csproj
      - name: Build Entity Tests
        run: dotnet build PurrBank_BackEnd/Tests/Entities.UnitTests/Entities.UnitTests.csproj
      - name: Run Entity Tests
        run:  dotnet test --no-build --verbosity normal PurrBank_BackEnd/Tests/Entities.UnitTests/Entities.UnitTests.csproj
      
          

    
    
